### PR TITLE
Fix Edit Post

### LINKED ISSUE #38: Edit Post Correctly
Edit post requirements
Add post requirements
Fix routes to edit post
Update correctly post

### PR DESCRIPTION
**Pull request by angel23v**
## Quick Info
Fix routes on the feed
Fix form for add  & edit post
Fix delete images

### CODE REVIEW

File: app/controllers/posts_controller.rb [hunk 1]
```diff
@@ -39,8 +40,15 @@ def update
       redirect_to root_path, alert: 'You are not authorized to update this post.'
       return
```
Comment (MauricioNC) [inline app/controllers/posts_controller.rb]: Why do you need a return here?

File: app/models/post.rb [hunk 2]
```diff
@@ -8,6 +8,28 @@ class Post < ApplicationRecord
...
+  end
+
+  private
+
+  def select_image(img_id)
+    blob_id = ActiveStorage::Blob.find_signed!(img_id).id
+
+    image = ActiveStorage::Attachment.find_by(blob_id: blob_id)
+
+    image.purge if image.present?
```
Comment (MauricioNC) [inline app/models/post.rb]: Remove empty spaces between lines

File: app/controllers/posts_controller.rb [hunk 3]
```diff
@@ -22,12 +22,13 @@ def create
 
   def index
     @posts = Post.user_post(current_user).order(created_at: :desc)
```
Comment (MauricioNC) [inline app/controllers/posts_controller.rb]:
```suggestion
    @posts = current_user.posts.order(created_at: :desc)
```

**Review by MauricioNC — CHANGES_REQUESTED** [review]

File: app/controllers/posts_controller.rb [hunk 4]
```diff
@@ -22,12 +22,13 @@ def create
...
   def edit
-    return if current_user == @post.user
-
-    redirect_to root_path, alert: 'You are not authorized to edit this post.'
+    unless current_user == @post.user
+      redirect_to root_path, alert: 'You are not authorized to edit this post.'
+    end
   end
 
   def show
```
Comment (JuanequeX) [inline app/controllers/posts_controller.rb:34]:
```suggestion
  def show; end
```

Comment (JuanequeX) [reply app/controllers/posts_controller.rb:34]: this is not necessary any more `@post = Post.find(params[:id])` because do you set the `set_post` in the private area

**Review by JuanequeX — CHANGES_REQUESTED** [review]

**Review by JuanequeX — APPROVED** [review]

**Review by MauricioNC — APPROVED** [review]

**Review by BlazeDex — APPROVED** [review]
